# Generated by Django 3.1.7 on 2021-03-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210310_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=200)),
                ('ccy', models.CharField(max_length=200)),
                ('base_ccy', models.CharField(max_length=200)),
                ('buy', models.CharField(max_length=200)),
                ('sale', models.CharField(max_length=200)),
            ],
        ),
    ]
